# Generated by Django 4.1 on 2022-08-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flavor')),
            ],
        ),
        migrations.CreateModel(
            name='FlavorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flavor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.size')),
            ],
        ),
        migrations.AddField(
            model_name='flavor',
            name='sizes',
            field=models.ManyToManyField(through='core.FlavorSize', to='core.size'),
        ),
    ]
